publishDir = "../docs"
resourceDir = "../resources"

baseURL = 'https://vinser.github.io/hugo_me/'

title = "My Hinode Site"
copyright = "Copyright Â© 2024 Serguei Vine."
paginate = 9
enableGitInfo = false

languageCode = "en-us"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true


[[module.imports]]
path = 'github.com/gethinode/hinode'
